name: Build macOS App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - run: npm run build

      - run: npm run dist

      - name: Upload macOS build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: room-management-mac-build
          path: dist/
