name: Test and Build macOS App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Test App with npm start
        run: |
          echo "Starting Electron app in test mode..."
          timeout 10 npm start || true
        continue-on-error: true

      - run: npm run build
      - run: npm run dist

      - name: Upload macOS App
        uses: actions/upload-artifact@v4
        with:
          name: RoomManagementApp-macos
          path: dist/*.dmg
